Fixed the fuck out of #536! (C) whatthecommit.com

diff --git a/Dockerfile.alpine b/Dockerfile.alpine
--- a/Dockerfile.alpine
+++ b/Dockerfile.alpine
@@ -1,90 +1,70 @@
-FROM daggerok/jboss-eap-6.4:6.4.20-alpine
-LABEL MAINTAINER='Maksim Kostromin <daggerok@gmail.com>'
-ENV PRODUCT='jboss-eap-6.4' \
-    JBOSS_USER='jboss'
-ENV JBOSS_USER_HOME="/home/${JBOSS_USER}" \
-    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download" \
-    JBOSS_EAP_PATCH='6.4.21'
-ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}" \
+FROM openjdk:8u212-jdk-alpine3.9
+LABEL MAINTAINER="Maksim Kostromin <daggerok@gmail.com>"
+ENV PRODUCT="jboss-eap-6.4"                                                         \
+    JBOSS_USER="jboss"
+ENV ADMIN_USER="admin"                                                              \
+    ADMIN_PASSWORD="Admin.123"                                                      \
+    JBOSS_USER_HOME="/home/${JBOSS_USER}"                                           \
+    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"    \
+    JBOSS_EAP_PATCH="6.4.22"
+ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                      \
+    ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                               \
     PATCHES_BASE_URL="${DOWNLOAD_BASE_URL}/${JBOSS_EAP_PATCH}"
 ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"
+USER root
+RUN ( apk fix     --no-cache || echo "cannot fix."         )                                    && \
+    ( apk upgrade --no-cache || echo "cannot upgrade."     )                                    && \
+    ( apk cache    -v  clean || echo "cannot clean cache." )                                    && \
+      apk add     --no-cache --update --upgrade                                                    \
+            busybox-suid bash wget ca-certificates unzip sudo openssh-client shadow curl        && \
+    echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                && \
+    sed -i "s/.*requiretty$/Defaults !requiretty/" /etc/sudoers                                 && \
+    addgroup --system -g 1001 -S ${JBOSS_USER}                                                  && \
+    adduser --system -h ${JBOSS_USER_HOME} -s /bin/ash -D -u 1001 ${JBOSS_USER} ${JBOSS_USER}   && \
+    usermod -a -G ${JBOSS_USER} ${JBOSS_USER}
 USER ${JBOSS_USER}
-RUN ( sudo apk fix --no-cache || echo 'cannot fix.' ) \
- && ( sudo apk upgrade --no-cache || echo 'cannot upgrade.' )
+EXPOSE 8080 8443 9990
+ENTRYPOINT ["/bin/ash", "-c"]
+CMD ["${JBOSS_HOME}/bin/standalone.sh -b 0.0.0.0"]
 WORKDIR /tmp
 ADD --chown=jboss ./install.sh .
-RUN ( standalone.sh --admin-only \
-      & ( sudo chmod +x /tmp/install.sh \
-          && install.sh \
-          && ( sudo apk cache -v clean || echo 'cannot clean cache.' ) \
-          && sudo rm -rf /tmp/* ) )
+RUN wget ${ARCHIVES_BASE_URL}/jboss-eap-6.4.0.zip                                                                                                  \
+          -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-6.4.0.zip                                                                    && \
+    unzip -q /tmp/jboss-eap-6.4.0.zip -d ${JBOSS_USER_HOME}                                                                                     && \
+    add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                                                                        && \
+    echo 'JAVA_OPTS="-Djava.io.tmpdir=/tmp -Djava.net.preferIPv4Stack=true -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"   \
+         ' >> ${JBOSS_HOME}/bin/standalone.conf                                                                                                 && \
+    ( standalone.sh --admin-only                                                                                                                   \
+      & ( sudo chmod +x /tmp/install.sh                                                                                                         && \
+          install.sh                                                                                                                            && \
+          sudo apk del --no-cache --no-network --purge busybox-suid unzip openssh-client shadow                                                 && \
+          ( sudo rm -rf /tmp/* /var/cache/apk /var/lib/apk /etc/apk/cache || echo "cleanup!" ) ) )
 WORKDIR ${JBOSS_USER_HOME}
 
-# ############################################### USAGE ##################################################
-# #                                                                                                      #
-# # FROM daggerok/jboss-eap-6.4:6.4.21-alpine                                                             #
-# #                                                                                                      #
-# # # debug:                                                                                             #
-# # ENV JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"        #
-# # EXPOSE 5005                                                                                          #
-# #                                                                                                      #
-# # # health-check:                                                                                      #
-# # HEALTHCHECK --timeout=1s \                                                                           #
-# #             --retries=33 \                                                                           #
-# #             CMD test `netstat -ltnp | grep 9990 | wc -l` -ge 1 || exit 1                             #
-# # # or:                                                                                                #
-# # HEALTHCHECK --timeout=1s \                                                                           #
-# #             --retries=33 \                                                                           #
-# #             CMD wget -q --spider http://127.0.0.1:8080/my-service/health || exit 1                   #
-# #                                                                                                      #
-# # # multi-deployment:                                                                                  #
-# # COPY --chown=jboss ./path/to/apps/*.war ./path/to/libs/*.war ${JBOSS_HOME}/standalone/deployments/   #
-# #                                                                                                      #
-# ########################################################################################################
-#
-# FROM openjdk:8u181-jdk-alpine3.8
-# LABEL MAINTAINER='Maksim Kostromin <daggerok@gmail.com>'
-# ENV PRODUCT='jboss-eap-6.4'                                                                            \
-#     JBOSS_USER='jboss'
-# ENV ADMIN_USER='admin'                                                                                 \
-#     ADMIN_PASSWORD='Admin.123'                                                                         \
-#     JBOSS_USER_HOME="/home/${JBOSS_USER}"                                                              \
-#     DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"                       \
-#     JBOSS_EAP_PATCH='6.4.5'
-# ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                                         \
-#     ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                                                  \
-#     PATCHES_BASE_URL="${DOWNLOAD_BASE_URL}/${JBOSS_EAP_PATCH}"
-# ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"
-# USER root
-# RUN ( apk fix     --no-cache || echo 'cannot fix.'         )                                        && \
-#     ( apk upgrade --no-cache || echo 'cannot upgrade.'     )                                        && \
-#     ( apk cache   -v   clean || echo 'cannot clean cache.' )                                        && \
-#       apk add     --no-cache --update --upgrade                                                        \
-#                   busybox-suid bash wget ca-certificates unzip sudo openssh-client shadow           && \
-#     echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                    && \
-#     sed -i 's/.*requiretty$/Defaults !requiretty/' /etc/sudoers                                     && \
-#     adduser -h ${JBOSS_USER_HOME} -s /bin/bash -D ${JBOSS_USER} ${JBOSS_USER}                       && \
-#     usermod -a -G ${JBOSS_USER} ${JBOSS_USER}
-# USER ${JBOSS_USER}
-# CMD /bin/bash
-# ENTRYPOINT standalone.sh
-# EXPOSE 8080 8443 9990 9999
-# WORKDIR /tmp
-# ADD --chown=jboss ./install.sh .
-# RUN wget ${ARCHIVES_BASE_URL}/jce_policy-8.zip                                                         \
-#          -q --no-cookies --no-check-certificate -O /tmp/jce_policy-8.zip                            && \
-#     unzip -q /tmp/jce_policy-8.zip -d /tmp                                                          && \
-#     ( sudo mv -f ${JAVA_HOME}/lib/security ${JAVA_HOME}/lib/backup-security || echo 'no backups.' ) && \
-#     sudo mv -f /tmp/UnlimitedJCEPolicyJDK8 ${JAVA_HOME}/lib/security                                && \
-#     wget ${ARCHIVES_BASE_URL}/jboss-eap-6.4.0.zip                                                      \
-#          -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-6.4.0.zip                         && \
-#     unzip -q /tmp/jboss-eap-6.4.0.zip -d ${JBOSS_USER_HOME}                                         && \
-#     add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                            && \
-#     echo 'JAVA_OPTS="-Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"             \
-#          ' >> ${JBOSS_HOME}/bin/standalone.conf                                                     && \
-#     sudo apk del --no-cache --no-network --purge                                                       \
-#                  busybox-suid unzip openssh-client shadow                                           && \
-#     sudo rm -rf /tmp/*.zip /tmp/*.tar.gz /var/cache/apk /var/lib/apk /etc/apk/cache || echo 'oops'  && \
-#     ( standalone.sh --admin-only                                                                       \
-#         & ( sudo chmod +x /tmp/install.sh && install.sh && rm -rf /tmp/install.sh ) )
-# WORKDIR ${JBOSS_USER_HOME}
+############################################### USAGE ##################################################
+#                                                                                                      #
+# FROM daggerok/jboss-eap-6.4:6.4.22-alpine                                                            #
+#                                                                                                      #
+# # debug:                                                                                             #
+# ENV JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"        #
+# EXPOSE 5005                                                                                          #
+#                                                                                                      #
+# # health-check:                                                                                      #
+# HEALTHCHECK --retries=33 \                                                                           #
+#             --timeout=1s \                                                                           #
+#             --interval=1s \                                                                          #
+#             --start-period=3s \                                                                      #
+#             CMD test `netstat -ltnp | grep 9990 | wc -l` -ge 1 || exit 1                             #
+# # or:                                                                                                #
+# HEALTHCHECK --retries=33 \                                                                           #
+#             --timeout=1s \                                                                           #
+#             --interval=1s \                                                                          #
+#             --start-period=3s \                                                                      #
+#             CMD wget -q --spider http://127.0.0.1:8080/my-service/health || exit 1                   #
+#                                                                                                      #
+# COPY --chown=jboss ./target/*.war ${JBOSS_HOME}/standalone/deployments/my-service.war                #
+#                                                                                                      #
+# # or multi-deployment:                                                                               #
+# COPY --chown=jboss ./path/to/apps/*.war ./path/to/libs/*.war ${JBOSS_HOME}/standalone/deployments/   #
+#                                                                                                      #
+########################################################################################################
diff --git a/Dockerfile.centos b/Dockerfile.centos
--- a/Dockerfile.centos
+++ b/Dockerfile.centos
@@ -1,96 +1,70 @@
-FROM daggerok/jboss-eap-6.4:6.4.20-centos
-LABEL MAINTAINER='Maksim Kostromin <daggerok@gmail.com>'
-ENV PRODUCT='jboss-eap-6.4' \
-    JBOSS_USER='jboss'
-ENV JBOSS_USER_HOME="/home/${JBOSS_USER}" \
-    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download" \
-    JBOSS_EAP_PATCH='6.4.21'
-ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}" \
+FROM centos:centos8
+LABEL MAINTAINER="Maksim Kostromin <daggerok@gmail.com>"
+ENV PRODUCT="jboss-eap-6.4"                                                         \
+    JBOSS_USER="jboss"
+ENV ADMIN_USER="admin"                                                              \
+    ADMIN_PASSWORD="Admin.123"                                                      \
+    JBOSS_USER_HOME="/home/${JBOSS_USER}"                                           \
+    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"    \
+    JBOSS_EAP_PATCH="6.4.22"
+ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                      \
+    ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                               \
     PATCHES_BASE_URL="${DOWNLOAD_BASE_URL}/${JBOSS_EAP_PATCH}"
-ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"
+ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"                                           \
+    JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk"
+USER root
+RUN yum update --security -y -q                                                                         && \
+    yum install -y -q                                                                                      \
+            wget ca-certificates unzip sudo openssh-clients zip net-tools curl java-1.8.0-openjdk-devel && \
+    echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                        && \
+    groupadd --system --gid 1001 ${JBOSS_USER}                                                          && \
+    adduser --system -m -d ${JBOSS_USER_HOME} -s /sbin/bash -g ${JBOSS_USER} --uid 1001 ${JBOSS_USER}   && \
+    usermod -a -G ${JBOSS_USER} ${JBOSS_USER}
 USER ${JBOSS_USER}
-RUN sudo yum update --security -y \
- && sudo yum update -y
+EXPOSE 8080 8443 9990
+ENTRYPOINT ["/bin/bash", "-c"]
+CMD ["${JBOSS_HOME}/bin/standalone.sh -b 0.0.0.0"]
 WORKDIR /tmp
 ADD --chown=jboss ./install.sh .
-RUN ( standalone.sh --admin-only \
-      & ( sudo chmod +x /tmp/install.sh \
-          && install.sh \
-          && sudo yum autoremove -y \
-          && sudo yum clean all -y \
-          && sudo rm -rf /tmp/*  ) )
+RUN wget ${ARCHIVES_BASE_URL}/jboss-eap-6.4.0.zip                                                                                                  \
+         -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-6.4.0.zip                                                                     && \
+    unzip -q /tmp/jboss-eap-6.4.0.zip -d ${JBOSS_USER_HOME}                                                                                     && \
+    add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                                                                        && \
+    echo 'JAVA_OPTS="-Djava.io.tmpdir=/tmp -Djava.net.preferIPv4Stack=true -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"   \
+         ' >> ${JBOSS_HOME}/bin/standalone.conf                                                                                                 && \
+    ( standalone.sh --admin-only                                                                                                                   \
+      & ( sudo chmod +x /tmp/install.sh                                                                                                         && \
+          install.sh                                                                                                                            && \
+          rm -rf /tmp/install.sh                                                                                                                && \
+          sudo yum autoremove -y                                                                                                                && \
+          sudo yum clean all -y                                                                                                                 && \
+          ( sudo rm -rf /tmp/* /var/cache/yum || echo "something was not removed..." ) ) )
 WORKDIR ${JBOSS_USER_HOME}
 
-# ############################################### USAGE ##################################################
-# #                                                                                                      #
-# # FROM daggerok/jboss-eap-6.4:6.4.21-centos                                                             #
-# #                                                                                                      #
-# # # debug:                                                                                             #
-# # ENV JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"        #
-# # EXPOSE 5005                                                                                          #
-# #                                                                                                      #
-# # # health check:                                                                                      #
-# # HEALTHCHECK --timeout=1s \                                                                           #
-# #             --retries=33 \                                                                           #
-# #             CMD test `netstat -ltnp | grep 9990 | wc -l` -ge 1 || exit 1                             #
-# # # or:                                                                                                #
-# # HEALTHCHECK --timeout=1s \                                                                           #
-# #             --retries=33 \                                                                           #
-# #             CMD wget -q --spider http://127.0.0.1:8080/my-service/health || exit 1                   #
-# #                                                                                                      #
-# # # multi deployment:                                                                                  #
-# # COPY --chown=jboss ./path/to/apps/*.war ./path/to/libs/*.war ${JBOSS_HOME}/standalone/deployments/   #
-# #                                                                                                      #
-# ########################################################################################################
-#
-# # FROM registry.access.redhat.com/rhel7:7.6-119 or rhel7-minimal:7.6-119
-# # https://access.redhat.com/containers/?tab=changeSummary
-# FROM centos:centos7.5.1804
-# LABEL MAINTAINER='Maksim Kostromin <daggerok@gmail.com>'
-# ENV PRODUCT='jboss-eap-6.4'                                                                            \
-#     JBOSS_USER='jboss'
-# ENV ADMIN_USER='admin'                                                                                 \
-#     ADMIN_PASSWORD='Admin.123'                                                                         \
-#     JDK_VERSION='jdk1.8.0_191'                                                                         \
-#     JBOSS_USER_HOME="/home/${JBOSS_USER}"                                                              \
-#     DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"                       \
-#     JBOSS_EAP_PATCH='6.4.5'
-# ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                                         \
-#     ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                                                  \
-#     PATCHES_BASE_URL="${DOWNLOAD_BASE_URL}/${JBOSS_EAP_PATCH}"
-# ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"                                                              \
-#     JAVA_HOME="/usr/lib/jvm/${JDK_VERSION}"
-# USER root
-# RUN yum update -y                                                                                   && \
-#     yum update --security -y                                                                        && \
-#     yum install -y wget ca-certificates unzip sudo openssh-client unzip zip net-tools               && \
-#     echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                    && \
-#     adduser -U -m -d /home/jboss -s /bin/bash jboss                                                 && \
-#     usermod -a -G ${JBOSS_USER} ${JBOSS_USER}
-# USER ${JBOSS_USER}
-# CMD /bin/bash
-# ENTRYPOINT standalone.sh
-# EXPOSE 8080 8443 9990 9999
-# WORKDIR /tmp
-# ADD --chown=jboss ./install.sh .
-# RUN wget ${ARCHIVES_BASE_URL}/${JDK_VERSION}.tar.gz                                                    \
-#          -q --no-cookies --no-check-certificate -O /tmp/${JDK_VERSION}.tar.gz                       && \
-#     sudo mkdir -p /usr/lib/jvm                                                                      && \
-#     sudo tar xzfz /tmp/${JDK_VERSION}.tar.gz -C /usr/lib/jvm/                                       && \
-#     wget ${ARCHIVES_BASE_URL}/jce_policy-8.zip                                                         \
-#          -q --no-cookies --no-check-certificate -O /tmp/jce_policy-8.zip                            && \
-#     unzip -q /tmp/jce_policy-8.zip -d /tmp                                                          && \
-#     ( sudo mv -f ${JAVA_HOME}/lib/security ${JAVA_HOME}/lib/backup-security || echo 'no backups.' ) && \
-#     sudo mv -f /tmp/UnlimitedJCEPolicyJDK8 ${JAVA_HOME}/lib/security                                && \
-#     wget ${ARCHIVES_BASE_URL}/jboss-eap-6.4.0.zip                                                      \
-#          -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-6.4.0.zip                         && \
-#     unzip -q /tmp/jboss-eap-6.4.0.zip -d ${JBOSS_USER_HOME}                                         && \
-#     add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                            && \
-#     echo 'JAVA_OPTS="-Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"'            \
-#          >> ${JBOSS_HOME}/bin/standalone.conf                                                       && \
-#     sudo yum autoremove -y                                                                          && \
-#     sudo yum clean all -y                                                                           && \
-#     sudo rm -rf /tmp/*.zip /tmp/*.tar.gz /var/cache/yum                                             && \
-#     ( standalone.sh --admin-only                                                                       \
-#       & ( sudo chmod +x /tmp/install.sh && install.sh && rm -rf /tmp/install.sh ) )
-# WORKDIR ${JBOSS_USER_HOME}
+############################################### USAGE ##################################################
+#                                                                                                      #
+# FROM daggerok/jboss-eap-6.4:6.4.22-centos                                                            #
+#                                                                                                      #
+# # debug:                                                                                             #
+# ENV JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"        #
+# EXPOSE 5005                                                                                          #
+#                                                                                                      #
+# # health-check:                                                                                      #
+# HEALTHCHECK --retries=33 \                                                                           #
+#             --timeout=1s \                                                                           #
+#             --interval=1s \                                                                          #
+#             --start-period=3s \                                                                      #
+#             CMD test `netstat -ltnp | grep 9990 | wc -l` -ge 1 || exit 1                             #
+# # or:                                                                                                #
+# HEALTHCHECK --retries=33 \                                                                           #
+#             --timeout=1s \                                                                           #
+#             --interval=1s \                                                                          #
+#             --start-period=3s \                                                                      #
+#             CMD wget -q --spider http://127.0.0.1:8080/my-service/health || exit 1                   #
+#                                                                                                      #
+# COPY --chown=jboss ./target/*.war ${JBOSS_HOME}/standalone/deployments/my-service.war                #
+#                                                                                                      #
+# # or multi-deployment:                                                                               #
+# COPY --chown=jboss ./path/to/apps/*.war ./path/to/libs/*.war ${JBOSS_HOME}/standalone/deployments/   #
+#                                                                                                      #
+########################################################################################################
